ServiceForMinibuses/ServiceForMinibuses.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace ServiceForMinibuses.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.ActiveMenuItem = "home";
            return View();
        }

        public ActionResult About()
        {
            ViewBag.ActiveMenuItem = "about";
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.ActiveMenuItem = "contact";
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ServiceForMinibuses/ServiceForMinibuses.Web/Controllers/StopController.cs
using ServiceForMinibuses.Manager;
using System.Web.Mvc;
using Models;
using ServiceForMinibuses.Web.Models;

namespace ServiceForMinibuses.Web.Controllers
{
    public class StopController : Controller
    {
        //
        // GET: /Stop/
         private readonly IStopStore _stopStore;

        public StopController(
         
            IStopStore stopStore)
        {
            _stopStore = stopStore;
        }
        public ActionResult CreateStop()
        {
            return View();
        }

        //
        // GET: /Stop/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Stop/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Stop/Create
        [HttpPost]
        public ActionResult CreateStop(CreateStopViewModel model)
        {
           
            if (ModelState.IsValid)
            {
                var stop = new Stop();
                stop.Name = model.Name;
                stop.XCoord = model.XCoord;
                stop.YCoord = model.YCoord;

                _stopStore.AddStop(stop);

                return RedirectToAction("Index", "Home");
            }
                return View();
        }

        public ActionResult ViewStops()
        {
            var model = new RouteListViewModel();
          

            return View("ViewStops", model);
        }
        //
        // POST: /Stop/Edit/5
        [HttpPost]
        public ActionResult EditStop(int id, string stopName)
        {
           
                var stop = _stopStore.GetStopById(id);
                stop.Name = stopName;
                _stopStore.UpdateStop(stop);
   
                return RedirectToAction("ViewRoutes", "Route");
         
        }

        //
        // GET: /Stop/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Stop/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }


        }
    }
}

ServiceForMinibuses/ServiceForMinibuses.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ServiceForMinibuses/ServiceForMinibuses.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}


<div class="home-style-text" id="rewiew-question">
    <div>Do you want to leave feedback?</div>

    <div class="clearfix">
        <div class="column w-10">
            <input type="radio" name="optionsRadios" id="feedbackYes" value="yes">
            <span>Yes</span>
        </div>
        <div class="column w-10">
            <input class="pT10" type="radio" name="optionsRadios" id="feedbackNo" value="no">
            <span>No</span>
        </div>
    </div>
</div>

<div id="review-textbox" class="visible-no pT10"><input type="text" placeholder="Enter your review">
</div>

@section Scripts {
    <script src="/kendoui/js/jquery.min.js"></script>
    <script src="/kendoui/js/kendo.all.min.js"></script>

    <script>
        var containerSelector = ('#rewiew-question');
        var container = $(containerSelector);
        container.on("change", '[type="radio"]', viewField);

        function viewField() {

            var checkedRadioButton = $(containerSelector + ' [type="radio"]:checked');

            if (checkedRadioButton[0].id == 'feedbackYes') {

                    $('#rewiew-question').toggleClass("visible-no");
                    $('#review-textbox').toggleClass("visible-no");
                }
        }

    </script>
}

ServiceForMinibuses/ServiceForMinibuses.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home page";
}

<div id="startGuestion" class="home-style-text">
    
    <div class="pT10">Do you want to create route or stop? </div>

    <div>
        <input type="radio" name="optionsRadios" id="optionsRadios1" value="yes">
        <span>Yes</span>
    </div>
    <div>
        <input type="radio" name="optionsRadios" id="optionsRadios2" value="no">
        <span>No</span>
    </div>

</div>

<div id="toDo" class="home-style-text visible-no">Do you want to do?</div>

<div class="pL20  visible-no" id="creatButtons">
    <div class="row pT10">
        <a href="@Url.Action("CreateRoute", "Route")"><span class="glyphicon glyphicon-plus"></span> Create route </a>
    </div>

    <div class="row pT10">
        <a href="@Url.Action("CreateStop", "Stop")"><span class="glyphicon glyphicon-plus"></span> Create stop</a>
    </div>
</div>




@section styles {
    <link rel="stylesheet" href="/kendoui/styles/kendo.common.min.css" />
    <link rel="stylesheet" href="/kendoui/styles/kendo.default.min.css" />


}

@section Scripts {
    <script src="/kendoui/js/jquery.min.js"></script>
    <script src="/kendoui/js/kendo.all.min.js"></script>

    <script>
        var containerSelector = ('#startGuestion');
        var container = $(containerSelector);
        container.on("change", '[type="radio"]', viewField);

        function viewField() {
        
            var checkedRadioButton = $(containerSelector + ' [type="radio"]:checked');

            if (checkedRadioButton[0].id == 'optionsRadios1') {

                    $('#creatButtons').toggleClass("visible-no");

                    $('#startGuestion').toggleClass("visible-no");

                    $('#toDo').toggleClass("visible-no");
                }
        }

    </script>
}